# Generated by Django 5.0.3 on 2024-03-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_otp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret_encrypted',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret_nonce',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret_tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
